/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 earth.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/earth.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={2.882}>
        <mesh
          geometry={nodes.logo.geometry}
          material={materials.logo}
          position={[1.002, 0.003, -0.023]}
          rotation={[Math.PI / 2, 0.132, -1.595]}
          scale={0.493}
        />
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.None}
          position={[0.264, 0, 0.963]}
          rotation={[-1.294, -0.032, 0.059]}
          scale={0.046}
        />
        <group
          position={[-1.013, 0.053, 0.274]}
          rotation={[Math.PI / 2, 0, -1.703]}
          scale={0.00061}
        >
          <mesh
            geometry={nodes.PANNEAU_SOLAIRE1_19_1.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            geometry={nodes.PANNEAU_SOLAIRE1_19_2.geometry}
            material={materials["BLANC PANNEAU SOLAIRE"]}
          />
        </group>
        <group
          position={[0.06, 0.009, -0.992]}
          rotation={[-1.068, 1.263, 1.41]}
          scale={0.026}
        >
          <mesh
            geometry={nodes.Sphere002__0001_1.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Sphere002__0001_2.geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes.Sphere002__0001_3.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Sphere002__0001_4.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            geometry={nodes.Sphere002__0001_5.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            geometry={nodes.Sphere002__0001_6.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            geometry={nodes.Sphere002__0001_7.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Sphere002__0001_8.geometry}
            material={materials["Material.008"]}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
        scale={2.476}
      />
    </group>
  );
}

useGLTF.preload("/earth.gltf");
