/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 earth.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={2.69}>
        <mesh geometry={nodes.logo.geometry} material={materials.logo} position={[1, 0.003, -0.023]} rotation={[Math.PI / 2, 0, -1.595]} scale={0.492} />
      </group>
      <group scale={3.882}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} position={[-0.75, 0, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.010} />
      </group>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} scale={2.376} />
    </group>
  )
}

useGLTF.preload('/earth.gltf')
